inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/migrate/*"
    - "db/seeds"
    - "config/initializers/*"
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
